### PR TITLE
Handle callables for ``content_type`` argument

### PR DESCRIPTION
**Pull request by elbart**
Handle callables for ``cornice.service.Service.content_type`` argument. For more details, see: http://cornice.readthedocs.io/en/latest/api.html#cornice.service.Service.

### CODE REVIEW

**Comment by elbart** [comment]
I found an error in the generated json, so I have to re-work on that.

**Comment by elbart** [comment]
Fix added. Generated output is now valid again. We may think of a CI step which automatically validates all generated files?

**Comment by elbart** [comment]
@gabisurita @Natim @leplatrem @delijati is one of you reviewing that soon? We are relying on this changes to continue with our work here :) In any case. Thanks for the great work on the project to everybody ;)

**Review by leplatrem — APPROVED** [review]
Sorry for the delay! I wasn't watching the repo :( 

Very good job!

**Comment by elbart** [comment]
merci @leplatrem ! Thanks a lot!

**Pull request merged**
